name: 'Setup Action'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      name: Install pnpm
      with:
        version: 7.32.4
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Cache nx cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml', 'package.json', 'nx.json', '**/project.json') }}
