name: Release Bot

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: [main, stable]
  release:
    types: [released, prereleased]

jobs:
  run:
    if: startsWith(github.head_ref, 'releases/') || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Setup PNPM
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
        with:
          version: 7.32.4

      - uses: statsig-io/statsig-publish-sdk-action@c0740fb8a2d4813522cc09bb8c4e826bb78ce6ab # main
        with:
          kong-private-key: ${{ secrets.KONG_GH_APP_PRIVATE_KEY }}
          npm-token: ${{ secrets.NPM_AUTOMATION_KEY }}
